# This workflow will build a Java project with Maven, and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-java-with-maven

# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: Java CI with Maven

on:
  push:
    branches: [ "fix-220" ]

jobs:
  build:

    # that requires a self-hosted runner with tag "arm64" bound to this repo
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'liberica'
        cache: maven
    - name: Test and Build with Maven
      run: ./mvnw -B package --file pom.xml

    - name: Create and publish native container image with spring maven plugin
      run: |
        ./mvnw -P native spring-boot:build-image \
          -DskipTests