# This workflow will build a Java project with Maven, and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-java-with-maven

# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: Spring Boot Paketo Buildpack Builds with Maven on Windows

on:
  schedule:
    - cron: "15,45 * * * *"
  push:
    branches: [ "main" ]

jobs:
  windows:
    timeout-minutes: 30
    runs-on: ['self-hosted', 'Windows']

    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'liberica'

    - name: Clean Docker Daemon
      run: docker system prune -a -f --volumes
      
    - name: Get pack cli for windows
      run: |
        Invoke-WebRequest -Uri https://github.com/buildpacks/pack/releases/download/v0.29.0/pack-v0.29.0-windows.zip -OutFile pack-v0.29.0-windows.zip
        Add-Type -AssemblyName System.IO.Compression.FileSystem ; [System.IO.Compression.ZipFile]::ExtractToDirectory("$PWD/pack-v0.29.0-windows.zip", "$PWD/pack")

    - name: Test and Build with Maven, Build image with pack
      run: |
        .\mvnw -B package --file pom.xml
        .\pack\pack.exe build -e BP_JVM_VERSION=17 --builder="paketobuildpacks/builder:base" -p target\spring-boot-demo-arm64-0.0.1-SNAPSHOT.jar built-on-windows-with-pack:jvm
      
    - name: Create JVM based container image with spring maven plugin
      run: .\mvnw spring-boot:build-image -D"spring-boot.build-image.imageName=built-on-windows:jvm" -D"spring-boot.build-image.builder=paketobuildpacks/builder:base" -DskipTests

    - name: Create native container image with spring maven plugin
      run: .\mvnw -P native spring-boot:build-image -D"spring-boot.build-image.imageName=built-on-windows:native" -D"spring-boot.build-image.builder=paketobuildpacks/builder:base" -DskipTests
